### ISSUE TITLE
llvm: libcxx won't compile (remove --with-libcxx?)

### ISSUE THREAD

**Issue by mikeandmore** [Linuxbrew/homebrew-core#1041]
libc++ needs a c++abi library, and by default, it's libcxxabi. Since we removed libcxxabi in pull request #4170 because it's buggy during linking, should we remove `--with-libcxx` as well?

Here's the error when building llvm `--with-libcxx`.

```
CMakeFiles/cxx.dir/__/src/algorithm.cpp.o: In function `std::__1::__rs_default::operator()()':
algorithm.cpp:(.text._ZNSt3__112__rs_defaultclEv+0x19): undefined reference to `__cxa_guard_acquire'
algorithm.cpp:(.text._ZNSt3__112__rs_defaultclEv+0x71): undefined reference to `__cxa_guard_release'
...
CMakeFiles/cxx.dir/__/src/typeinfo.cpp.o:(.data.rel.ro._ZTISt10bad_typeid[_ZTISt10bad_typeid]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libc++.so.1.0] Error 1
```

**Comment by sjackman** [comment]
@rwhogg Who knows the most about `llvm` and `clang` on Linux? There's many questions for which I don't have answers.

**Comment by rwhogg** [comment]
I'm no expert (@maxim-belkin might know more than me), but my understanding is that libc++ (libcxx and libc++ are the same thing) isn't used on Linux any more because of https://github.com/Linuxbrew/brew/pull/63.

So, even if it was built, it would not get used by brew-installed programs at all. You might be able to use it for your own programs manually compiled with `clang++`.

I'm therefore :+1: on removing this on Linux. Mac is another story.

**Comment by sjackman** [comment]
Fine by me.

**Comment by maxim-belkin** [comment]
Closing this as `libcxx` is not built by default on Linux
