### ISSUE TITLE
cmake: $(brew --prefix)/include : $(brew --prefix)/lib are not added to default configuration

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/homebrew-core#1197]
For brewed cmake, including those location would be a sane default and absence of those location in default search paths seem like a bug to me.

**Comment by eiennohito** [comment]
Path configuration is done inside `<cmake>/share/cmake/Modules/Platform`.

Probably, we should append homebrew paths there in postinstall step.

**Comment by sjackman** [comment]
`brew install gcc` also resolves this issue, as it includes these two paths by default. That's my recommended solution. Does that work for you?

**Comment by eiennohito** [comment]
I need to check, but I believe `find_package` and friends searches only in CMake paths, not in compiler ones.

**Comment by sjackman** [comment]
Ah, sad boat. I like autoconf because it checks whether your compiler can find the necessary headers and libraries.

**Comment by sjackman** [comment]
Which formula are you attempting to build that's failing and led you to this solution?

**Comment by eiennohito** [comment]
It's not formulas, but using brewed cmake to build some research apps that are built with cmake.

**Comment by sjackman** [comment]
Now that I've looked at its contents, yes, `UnixPaths.cmake` should definitely be customized for Linuxbrew. In particular all the default system paths that are not relevant for Linuxbrew should be removed. System libraries can cause a lot of havoc when a system library is found instead of the Linuxbrew library. Would you like to take a go at this PR?

**Comment by eiennohito** [comment]
Ok, I will.
