### ISSUE TITLE
autoconf: depends on libtool for Linuxbrew

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/homebrew-core#1473]
Formula actually already implies that:
```ruby
 27     # force autoreconf to look for and use our glibtoolize
 28     inreplace "bin/autoreconf.in", "libtoolize", "glibtoolize"
 29     # also touch the man page so that it isn't rebuilt
 30     inreplace "man/autoreconf.1", "libtoolize", "glibtoolize"
```

My suggestions is to consider using the unusual
```ruby
depends_on "libtool" => :run
```

This change would require re-checking dependencies on `libtool` for all formulas that depend on `autoconf`.

**Comment by maxim-belkin** [comment]
Any thoughts, ideas?
@sjackman @rwhogg @DoomHammer

**Comment by DoomHammer** [comment]
Not an expert but seems reasonable. Autotools are usually used as a bunch anyway.

**Comment by rwhogg** [comment]
This is harmless and reasonable ( :+1: ), but I'm not sure it's necessary.

I'm not personally convinced that "is designed to work with brewed libtool" implies "depends on brewed libtool" though. That could be an issue if
a) brewed autoconf fails (to either build or run properly) if brewed libtool is missing regardless of whether autoconf-built programs needed libtool or not OR
b) a significant number of formulae `depends_on` autoconf but don't `depends_on` libtool and fail when the latter is not installed

If a) is true, then I'm :100: on this change, but if that were the case I suspect we would have found out when we bottled autoconf. If b) is true, then I suspect upstream probably would have a lot of issues with it too, so that seems unlikely.

> This change would require re-checking dependencies on libtool for all formulas that depend on autoconf

Would it? I don't think redundant dependencies on libtool would be a huge problem.

**Comment by maxim-belkin** [comment]
OK, so here is the deal:
`autoreconf` is the only script from `autoconf` package that uses `glibtoolize`.
Have a look at `$(brew --prefix autoconf)/bin/autoreconf`. There is a line (114):
```perl
my $glibtoolize = $ENV{'LIBTOOLIZE'} || 'glibtoolize';
```
and line 550
```perl
xsystem_hint ("glibtoolize is needed because this package uses Libtool", $glibtoolize);
```
It turns out that `autoconf` might be OK without `libtool` if `glibtoolize` is not used.

For example, the following packages use `autoreconf` but do not directly depend on `libtool`:
```bash
$ cd $(brew --repo)/Library/Taps/homebrew/homebrew-core/Formula
$ grep -L 'depends_on "libtool"' $(grep -l 'autoreconf' *)
arp-scan.rb
autoconf.rb
byobu.rb
darkstat.rb
datetime-fortran.rb
deja-gnu.rb
dosfstools.rb
duti.rb
fcgiwrap.rb
fish.rb
giflossy.rb
goaccess.rb
jo.rb
knock.rb
lha.rb
libetonyek.rb
lsh.rb
mp3unicode.rb
ncdc.rb
ncdu.rb
osmfilter.rb
osslsigncode.rb
pdftoedn.rb
ppl@0.11.rb
rdup.rb
rlwrap.rb
schismtracker.rb
scrypt.rb
scsh.rb
shairport-sync.rb
tarsnap.rb
twemcache.rb
unpaper.rb
zpython.rb
```

So, I guess the choice was made to add `libtool` dependency when it is needed directly in the formula that is being built instead of `autoconf`. This seems weird but I can leave with that.
