### ISSUE TITLE
continous integration: what's missing to catch regressions?

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1568]
Is there any doc on linuxbrew's continous integration? (or link to its settings)

Does it run continously ?
What frequency? 
Is it run each time a PR is updated/submitted?
Is it run each time theres's a merge with homebrew upstream?
Is it run on every formula in homebrew-core (and select taps) ?
In what environments?

How come it didn't automatically find regressions before users run into issues?
eg: just filed 3 more today https://github.com/Linuxbrew/homebrew-core/issues/1567 https://github.com/Linuxbrew/homebrew-core/issues/1566 https://github.com/Linuxbrew/homebrew-core/issues/1562

What would it take for CI to automatically find those ahead of time? (and perhaps revert culprit PR's/merge's)

Could users be warned ahead of time to avoid trying to install something known not to work via CI, eg: 
```
brew install --check-ci X
error: X last failed on your system[eg ubuntu16.04] [doc to logs]
``` 

likewise with `brew upgrade --check-ci` which would filter issues known not to work

**Comment by sjackman** [comment]
> Is there any doc on linuxbrew's continous integration? (or link to its settings)

No, sorry. Just these docs for Homebrew, which haven't been updated for Linuxbrew.
https://github.com/Linuxbrew/brew/blob/master/docs/Brew-Test-Bot-For-Core-Contributors.md

The settings are here:
https://github.com/Linuxbrew/homebrew-core/blob/master/.travis.yml
https://github.com/Linuxbrew/homebrew-core/blob/master/circle.yml

> Does it run continously ?

Yes.

> What frequency?

With every push to `master` or a pull request.

> Is it run each time a PR is updated/submitted?

Yes.

> Is it run each time theres's a merge with homebrew upstream?

Yes, but these CI runs time out after one hour (Travis) and two hours (Circle), so are not complete.

> Is it run on every formula in homebrew-core (and select taps) ?

It runs for those formula that have been modified by a push.

> In what environments?

Ubuntu 12 on Travis and Ubuntu 14 on Circle. Different versions by design choice to ensure that bottles built on Ubuntu 14 can run on Ubuntu 12.

> How come it didn't automatically find regressions before users run into issues? eg: just filed 3 more today #1567 #1566 #1562

Those formula have not yet been modified to work on Linuxbrew, and have not been tested on CI.

> What would it take for CI to automatically find those ahead of time? (and perhaps revert culprit PR's/merge's)

Submit a pull request to modify those formula, and they'll be tested by CI. Once a formula has been bottled for Linuxbrew once, it'll be tested by us on every subsequent merger of Homebrew/core into Linuxbrew/core.

> Could users be warned ahead of time to avoid trying to install something known not to work via CI, eg:

```
brew install --check-ci X
error: X last failed on your system[eg ubuntu16.04] [doc to logs]
likewise with brew upgrade --check-ci which would filter issues known not to work
```

If a formula has a bottle for Linuxbrew, then it's known to work on Linuxbrew.
If a given formula has an open pull request against it tagged `build-error`, then it's known not to work on Linuxbrew. After you install a formula that's known to fail, it lists open issues against that formula fetched from GitHub.
Otherwise, the status of those formula is unknown on Linux.

The trick would be in warning a user before they attempt the install that the formula is known not to work on Linuxbrew, without a bunch of API calls to GitHub.

**Comment by timotheecour** [comment]
> Ubuntu 12 on Travis and Ubuntu 14 on Circle
ubuntu 12.04 is reaching end of life in Apr-2017: https://www.ubuntu.com/info/release-end-of-life 
why not 14.04 and 16.04? Or at least adding a 16.04 test?

**Comment by timotheecour** [comment]
What about running each formula (at least once) that is in homebrew but not yet modified in linuxbrew, then reporting in some location the last know status per formula?

**Comment by sjackman** [comment]
> ubuntu 12.04 is reaching end of life in Apr-2017: https://www.ubuntu.com/info/release-end-of-life
why not 14.04 and 16.04? Or at least adding a 16.04 test?

One goal of Linuxbrew is to support old and still used distros that are common in industry and academia, which is why we test on Ubuntu 12. It'd be good to also test on Ubuntu 16 on Travis.

**Comment by sjackman** [comment]
> What about running each formula (at least once) that is in homebrew but not yet modified in linuxbrew, then reporting in some location the last know status per formula?

It's a good plan. No one has done it yet. The build logs would need to be posted somewhere publicly accessible. Any formula with a `:x86_64_linux` bottle is known to work on Linuxbrew. The rest are unknown status.
