### ISSUE TITLE
Make `Circle log` public (with a script that removes credentials)

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#1581]
Would help with https://github.com/Linuxbrew/homebrew-core/pull/1578#issuecomment-272482989 and other similar cases, eg:

> Sorry that the Circle log is not public. It contains credentials.

couldn't a script be run with `sed s/secret_credential=.*/HIDDEN/` ? (ran automatically when circle is run)

**Comment by sjackman** [comment]
The Circle web app itself cannot be made public, but it could be possible to scrub the logs like this, and then upload them somewhere, like GitHub. I won't personally be tackling this project due to a lack of time. We hope that most issues are replicated in both Travis and Circle, but that's not always true.
