### ISSUE TITLE
The newest ncurses fails to build due to Ada

### ISSUE THREAD

**Issue by netheril96** [Linuxbrew/homebrew-core#2683]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

The installation failed with complete logs at https://gist.github.com/netheril96/24d5bdb83c05c92823658cf71726ebfb

The line that fails is

```
gnatbind -aO. -aO../src -aO./../src -x tour.ali
gnatlink tour.ali -L../lib -lAdaCurses -L../../lib -lformw -lmenuw -lpanelw -lncursesw -Wl,-rpath,/home/export/online1/swyf/swthuem/tmp/ncurses-20170520-30540-8jgrr3/ncurses-6.0/lib
../../lib/libncursesw.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: ld returned 1 exit status
gnatlink: error when calling /usr/bin/gcc
gnatmake: *** link failed.
```
https://gist.github.com/netheril96/24d5bdb83c05c92823658cf71726ebfb#file-03-make-L1785

Because my OS is old, I installed a new version of gcc and glibc with homebrew. But brewed gcc does not come with Ada for unknown reasons, so that the `gnatlink` here points to the system one, therefore linking the object to old standard library.

This should be a common issue as many linuxbrew users use it exactly for the purpose of obtaining up-to-date software on an old linux.

The solution may be either build Ada with brewed gcc, or disable the Ada part in the ncurses formula.

**Comment by sjackman** [comment]
Thanks for the bug report, Siyuan. I'd accept a PR to disable `ada` in `ncurses`.

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `ncurses`.
Another possible workaround for you is `brew install --force-bottle ncurses`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
