### ISSUE TITLE
bdw-gc download failure

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-core#2888]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Simple download failure. It is weird as I can download that file quite easily via Chrome.
```
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "bdw-gc"
Download failed: http://www.hboehm.info/gc/gc_source/gc-7.6.0.tar.gz
```

**Comment by sjackman** [comment]
Try…
```sh
brew fetch bdw-gc
```
or if that fails, as a work around
```sh
curl -L -o $(brew --cache -s bdw-gc) http://www.hboehm.info/gc/gc_source/gc-7.6.0.tar.gz
```

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `bdw-gc`.
Another possible workaround for you is `brew install --force-bottle bdw-gc `, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
