### ISSUE TITLE
Upgrading dependencies of curl and gcc fails

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/homebrew-core#304]
Logs: https://gist.github.com/cdfd86bb608066b66d396309842d0476

mpfr is a gcc dependency, so:
1. Homebrew removes simlinks to mpfr
2. Homebrew tries to call gcc that depends on mpfr
3. gcc can't find mpfr library
4. Build fails

**Comment by DoomHammer** [comment]
This is not the only dependency that is causing problems during update. Similar thing with `openssl` (which is a dep of `curl`).

**Comment by sjackman** [comment]
Hi, Arseny. This unfortunately is a known bug. The workaround is:
```
LD_LIBRARY_PATH=`brew --prefix mpfr`/lib brew upgrade mpfr
```
Is there a reason that you're not using the precompiled bottle of `mpfr`?

**Comment by eiennohito** [comment]
I probably should use precompiled bottle here (was forcing homebrew to build everything from sources).

Thank you for the workaround. It worked.

**Comment by sjackman** [comment]
Glad to hear the the workaround worked for you.

**Comment by DoomHammer** [comment]
Any ideas how to incorporate this workaround into Linuxbrew itself? Quite many packages (in my opinion) are affected by it which, unfortunately, affects the UX.

**Comment by sjackman** [comment]
The user only experiences this bug if they build from source rather than pouring bottles, so it has become less of an issue now. It still affects `openssl` which is not `cellar :any`. It would be great to fix that. I believe it's possible.

I definitely want to fix this bug. The quick hack is to incorporate this workaround and set `LD_LIBRARY_PATH` to `#{formula.lib}:#{formula.opt_lib}`. See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/ENV/std.rb#L64

I haven't done this because I can think of situations where it would be break the build because it picks up the old version of the library before the one that is currently being built (after compile but before install). We could just apply the patch and wait and see if things break. Maybe it doesn't break in actuality. This is why the existing formula is unlinked before it's upgraded.

Perhaps a better solution is to set the RPATH of installed formula to include the `lib` directory of all of their dependencies followed finally by `$HOMEBREW_PREFIX/lib` as a backup. That way unlinking libraries won't affect the programs that require them. This is how Mac Homebrew does it (not by using RPATH, but a similar mechanism of specifying the full path to all dependent libraries).

**Comment by sjackman** [comment]
See also #47

**Comment by DoomHammer** [comment]
I like the RPATH approach. Isn't it limited to some arbitrary length though?

**Comment by sjackman** [comment]
Hmm. Maybe. I have no idea what that limit is. That could be a problem. I don't think so though. The RPATH of GHC executables is gigantic.

```
$ patchelf --print-rpath `which pandoc` |wc
      1       1   14157
```

**Comment by DoomHammer** [comment]
The more I live on this world the scarier creatures I encounter...

**Comment by sjackman** [comment]
Truly… frightening…

**Comment by DoomHammer** [comment]
Bitten once more by `brew upgrade openssl`. What could we do about it besides hacking around `brew upgrade` to perform differently when upgrading one of "special" formulae?

**Comment by sjackman** [comment]
My first thought is that the RPath of executables should include the `Cellar/package/version/lib` directory of the libraries against which they were built. Backup plan would be that we can set `LD_LIBRARY_PATH` as needed during `brew upgrade`.

**Comment by sjackman** [comment]
We now set `LD_LIBRARY_PATH` to `#{formula.lib}:#{formula.opt_lib}` during `brew install` and `brew upgrade`.
