### ISSUE TITLE
If passwordless sudo is enabled for user (or commands brew install uses) no prompt for where to install linuxbrew

### ISSUE THREAD

**Issue by dragon788** [Linuxbrew/homebrew-core#3108]
BACKGROUND:
I was installing Linuxbrew on my laptop after refreshing my OS and I had temporarily setup sudo with NOPASSWD for doing all the apt installs and other things that repeatedly prompt for sudo which prompts for a password after X minutes or in every new shell/terminal unless overridden.

ISSUE:
When I went to install Linuxbrew it checked for sudo access and immediately installed to the /home/linuxbrew/.linuxbrew location without even prompting me whether I would like to put it somewhere else.

DESIRED STATE:
I would greatly prefer to have a say in the install location even if I do have sudo rights and could place it outside of my home directory.

REPRODUCING THE ISSUE:
Give your user temporary NOPASSWD sudo rights.

To avoid hosing your system use this command which tests the file before putting it in place, the `zz` in front is to ensure it is the last file applied. Use `sudo -l` to see what rights your user has.

`echo "${USER} ALL=NOPASSWD: ALL" > /tmp/mytmp.sudoers && visudo -c -f /tmp/mytmp.sudoers && sudo chown root:root /tmp/mytmp.sudoers && sudo mv /tmp/mytmp.sudoers /etc/sudoers.d/zz_brewinstall`

Now install Linuxbrew via the default ruby method and you won't get prompted for an install location because it tests for `sudo` rights and chooses the install based on that rather than testing after you have selected the `/home/linuxbrew/.linuxbrew` path that you have the ability to sudo and create the path and if it fails fall back to using your own home directory.

**Comment by sjackman** [comment]
`/home/linuxbrew/.linuxbrew` is the default and preferred installation path for Linuxbrew when the user has write access or sudo access to that directory.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

To install in a different directory, see the Alternative Installations instructions at http://linuxbrew.sh/#alternative-installation
