### ISSUE TITLE
`gnupg2` and `gpg-agent` in conflict

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/homebrew-core#311]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Both `gpg-agent` and `gnupg2` provide locale for `gnupg2.mo`. They are the same size and according to `diff` identical though, obviously, they can't be both linked at the same time.

**Comment by rwhogg** [comment]
This looks like it might affect upstream too.

**Comment by DoomHammer** [comment]
Cannot check whether the same occurs on OS X as I lack the machine to test on :) @Linuxbrew/core someone willing to take a look?

**Comment by DomT4** [comment]
No locale at all is generated for `gpg-agent` or `gnupg2` on OS X, at least in the default configuration, although locale is generated for `gnupg21` in the Versions tap.

Without checking, it's possible that the problem is that Linuxbrew ignores `keg_only`, enabling the formulae discussed here to "discover" it during the `configure` process and that switch is on-by-default, so you end up with a conflict that is guarded from happening on OS X.

I suspect passing `--disable-nls` to `./configure` will resolve the issue.

**Comment by DoomHammer** [comment]
Will try this. Thanks, @DomT4!

**Comment by DoomHammer** [comment]
After removing the obstacles everything works like a charm. Thanks again, @DomT4 !

**Comment by DomT4** [comment]
No worries! Glad you got it all sorted.
