### ISSUE TITLE
brew install util-linux fails on fedora

### ISSUE THREAD

**Issue by sandeep-gh** [Linuxbrew/homebrew-core#3367]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/15610e4ce81a26b2946f368fe8af5fa1
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

 
To help us debug your issue please explain:
- What you were trying to do (and why)
Install util-linux because it is a dependency for postgis
- What happened (include command output)
Failed with error message
```
See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory '/tmp/util-linux-20170728-18318-7liaam/util-linux-2.29'
Makefile:11744: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/tmp/util-linux-20170728-18318-7liaam/util-linux-2.29'
Makefile:11436: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/util-linux-20170728-18318-7liaam/util-linux-2.29'
Makefile:11738: recipe for target 'install' failed
make: *** [install] Error 2
```
- Step-by-step reproduction instructions (by running `brew install` commands)
1. Cloned brew from github
2. brew update
3. brew install postgis (which fails on util-linux)
4. brew install util-linux

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
```
/usr/bin/install: cannot remove '/usr/share/bash-completion/completions/blkid': Permission denied
```
https://gist.github.com/anonymous/15610e4ce81a26b2946f368fe8af5fa1#file-02-make-L1016

**Comment by sjackman** [comment]
I feel like this issue has come up before, but I wasn't able to find it by searching the issues. It's a shot in the dark, but try…
```sh
brew install bash-completion util-linux
```

**Comment by sandeep-gh** [comment]
Removing bash-completion did the trick. Thank you.
