### ISSUE TITLE
systemd does not find perl from path

### ISSUE THREAD

**Issue by wookoouk** [Linuxbrew/homebrew-core#3471]
When installing `systemd` via brew the make script tests for /usr/bin/perl instead of looking on PATH.
As I am running this on a institute HPC I am not able to install the required `XML::Parser` on the /usr/bin/perl version of perl for the installation to complete:

```
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.10.1
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
```

Is there a way around this (I know it is something systemd is doing, not brew) but I need it to use the perl installed with brew.

Thank you

**Comment by wookoouk** [comment]
I might have figured it out:

`export INTLTOOL_PERL=/PATH/TO/BREW/bin/perl`
`brew install systemd`

**Comment by wookoouk** [comment]
installing intltool has the same issue, which can be solved with:
```export PERL=/PATH/TO/BREW/bin/perl```

**Comment by Char-Aznable** [comment]
I encountered the exactly the same problem for systemd. The build environment is picking up perl from /usr/bin/perl instead of the linuxbrew perl. This causes compilation error in building pulseaudio from source during "make install":
erl ./xmltoman pulseaudio.1.xml > pulseaudio.1 || rm -f pulseaudio.1
perl ./xmltoman esdcompat.1.xml > esdcompat.1 || rm -f esdcompat.1
perl ./xmltoman pax11publish.1.xml > pax11publish.1 || rm -f pax11publish.1
perl ./xmltoman pacat.1.xml > pacat.1 || rm -f pacat.1
perl ./xmltoman pacmd.1.xml > pacmd.1 || rm -f pacmd.1
perl ./xmltoman pactl.1.xml > pactl.1 || rm -f pactl.1
perl ./xmltoman pasuspender.1.xml > pasuspender.1 || rm -f pasuspender.1
perl ./xmltoman padsp.1.xml > padsp.1 || rm -f padsp.1
perl ./xmltoman pulse-daemon.conf.5.xml > pulse-daemon.conf.5 || rm -f pulse-daemon.conf.5
perl ./xmltoman pulse-client.conf.5.xml > pulse-client.conf.5 || rm -f pulse-client.conf.5
perl ./xmltoman default.pa.5.xml > default.pa.5 || rm -f default.pa.5
perl ./xmltoman pulse-cli-syntax.5.xml > pulse-cli-syntax.5 || rm -f pulse-cli-syntax.5
perl ./xmltoman start-pulseaudio-x11.1.xml > start-pulseaudio-x11.1 || rm -f start-pulseaudio-x11.1
Can't load '/home/caznable/.linuxbrew/Cellar/pulseaudio/11.1/libexec/lib/perl5/x86_64-linux-thread-multi/auto/XML/Parser/Expat/Expat.so) at /usr/lib64/perl5/DynaLoader.pm line 200. 
 at /home/caznable/.linuxbrew/Cellar/pulseaudio/11.1/libexec/lib/perl5/x86_64-linux-thread-multi/XML/Parser.pm line 18
Compilation failed in require at /home/caznable/.linuxbrew/Cellar/pulseaudio/11.1/libexec/lib/perl5/x86_64-linux-thread-multi/XML/Parser.pm line 18.
BEGIN failed--compilation aborted at /home/caznable/.linuxbrew/Cellar/pulseaudio/11.1/libexec/lib/perl5/x86_64-linux-thread-multi/XML/Parser.pm line 22.
Compilation failed in require at ./xmltoman line 20.
....
Perl: /usr/bin/perl
...

**Comment by iMichka** [comment]
I have found a solution for that, see #4499

There are instructions on how to fix this. The issue has been marked as easy and a pull request is welcome. I am willing to guide people through the process if there are any questions.

**Comment by Char-Aznable** [comment]
The solution in #4499 didn't help with pulseaudio. I have put
ENV.prepend_path "PERL5LIB", "#{Formula["intltool"].libexec}/lib/perl5" unless OS.mac? 
but this wasn't used by configure because NLS is disabled, which means intltool is not needed at all for compilation. The actual error I post has something to do with the build system picking up the wrong perl:
/usr/bin/perl, which is a very old one on the OS, instead of the brew provided one.

**Comment by iMichka** [comment]
I see. Sorry for the confusion, it is because the first error reported in this issue was about the missing XML::Parser perl module.

What OS are you using? I will need to reproduce this to be able to find a solution. It may be worth opening a new issue, and filing out the issue template, so I have the full information about your setup.
