### ISSUE TITLE
request(/question?): (would it be easy/what would it take to) support cask for AppImages(?)

### ISSUE THREAD

**Issue by emanresusername** [Linuxbrew/homebrew-core#4357]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install apps like [hyper](https://github.com/zeit/hyper/releases) or [etcher](https://etcher.io/) that are distributed as [AppImages](https://appimage.org/)
- What happened (include command output)
`Error: Homebrew Cask is only supported on macOS`
- What you expected to happen
i guess it'd download the the `.AppImage` `chmod +x` on it and then execute it
in my experience, that then prompts if you want to register it with your system and then it works like a regular app from then on
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew cask install hyper`

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

**Comment by iMichka** [comment]
We currently do not have any infrastructure for that; and no ressources to allocate to work on that. So if you volunteer we would accept pull requests to make this work. There are surely some technical details to sort ou before starting working on this.

**Comment by emanresusername** [comment]
yeah, i don't know too much about how homebrew cask internals work
but assuming the barrier to entry figuring that out isn't too high (or if we'd wanna take a totally different approach here?) i'd be willing to take a whack at it :+1:

**Comment by iMichka** [comment]
I do not know much about the Cask code neither. You can find it here and have a look:
https://github.com/Linuxbrew/brew/tree/master/Library/Homebrew/cask/lib

I would say that ideally it should integrate with cask, but that may be difficult. Some code would need to go upstream (to Homebrew/brew). You could start with a tap (like our developer tools tap for example); and add the necessary commands to build a proof of concept.

I will close this issue, but feel free to continue the discussion here.

**Comment by emanresusername** [comment]
cool, ok, i'll open some similar issues with some other repos that are in line with this and see if those maintainers/communities have ideas on the best ways to go about this

**Comment by probonopd** [comment]
Ah, I understand, https://github.com/athrunsun/homebrew-linuxbinary is about installing binaries. It should be easy for them to implement support for AppImages, since an AppImage is really nothing else  but an executable binary. They could even leverage data from https://github.com/AppImage/AppImage.github.io.

**Comment by iMichka** [comment]
Yes, you do not really need a package manager. The only advantage you have (and this why brew cask exists) is that you can do a regular "brew update" and get updates for you libraries AND for you apps.

**Comment by emanresusername** [comment]
yeah i see both sides of it
for me personally, osx just crapped out on me and i was thrust into this 😢 
but also just chatting with other devs who are just defaulting to osx by force of habbit
it feels really good to be able to respond to linux-adoption-anxiety (both my own and others) with, "it's cyool gyuys! you still have all that `brew` goodness you know and love" (even if it's not *strictly necessary*) 😄

**Comment by athrunsun** [comment]
I started appimage tap [here](https://github.com/athrunsun/homebrew-appimage), however I'm having problems installing any one of them because linuxbrew is complaining:
> Error: Failure while executing: ldd /home/athrun/.linuxbrew/Cellar/hyper-appimage/1.4.8/hyper-1.4.8-x86_64.AppImage
>    not a dynamic executable

Why does brew use `ldd` here?

**Comment by athrunsun** [comment]
Well, I finally figure it out myself - I don't if this is documented but by looking at `Formula` class's source code in linuxbrew, there's a `cxxstdlib_check` method:
```ruby
def cxxstdlib_check(check_type)
      define_method(:skip_cxxstdlib_check?) { true } if check_type == :skip
end
```

So I go ahead and add `cxxstdlib_check :skip` to every appimage formula and it works.

@emanresusername Have a try and let me know how you feel and what you think.

**Comment by probonopd** [comment]
@athrunsun thanks for looking into adding AppImage support. However, I wonder whether it is really a good use of time and resources to manually write one `.rb` file per application, and having to manually update this file every time upstream releases a new version (which can be very cumbersome, e.g., in the case of continuous builds).

Maybe you are interested in the data we are collecting in the [AppImageHub](https://github.com/AppImage/appimage.github.io/) central directory of available AppImages.

We are currently working on providing a JSON feed for all the AppImages in the directory:
https://appimage.github.io/feed.json

**Comment by emanresusername** [comment]
@athrunsun looks great to me!
using vlc and hyper appimages from there now :sunglasses:

@probonopd 's suggestion makes a lot of sense too, idk the "homebrew way" to take advantage of that though 🤔 

i know homebrew-cask had a mechanism for [dynamic download url's](https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/audacity.rb#L5#L15)

idk if there's something similar here?

**Comment by athrunsun** [comment]
@probonopd I'm building all the formulaes exactly according to [AppImageHub](https://appimage.github.io/apps/), I won't even be able to know those appimage apps without the information you provided.

I didn't try [AppImageUpdate](https://appimage.github.io/AppImageUpdate/) yet but according to the page https://appimage.github.io/apps/, only a small amount of apps can use AppImageUpdate to "update AppImages from their upstream location".

1. If AppImageUpdate is able to support more apps, it'll be unncessary to create [homebrew-appimage](https://github.com/athrunsun/homebrew-appimage) in the first place. It is because AppImage doesn't provide a centralized place where I can manage (install, upgrade, remove, etc., just like what homebrew did) my appimage apps, that I made that homebrew tap. (Please correct me if AppImageUpdate is able to do this)
2. The [JSON feed](https://appimage.github.io/feed.json) doesn't provide download urls directly, but a centralized place to tell me "where you can find download urls", which means I'll have to go through each "Install" url to extract the real download url and put it in my formula `.rb` file. This is weird when there's already AppImageUpdate, if I'm able to do it, why can't AppImageUpdate?
3. @emanresusername currently all appimage apps I collected in my tap provides a fixed url to download, if there're appimage apps with temporary download url, we can surely use the technique you mentioned.

**Comment by emanresusername** [comment]
oh yeah, was just brainstorming if there was a way to avoid having to manually maintain each file and leverage that hub
maybe the Formula directory (or parts of it) could be generated programatically using the hub
... but maybe that's heading down [this rabbit hole](https://xkcd.com/1629/) 😆 
![xckd 1629 tools](https://imgs.xkcd.com/comics/tools.png)
