### ISSUE TITLE
brew install source-highlight:configure: error: Could not find a version of the Boost::Regex library!

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/homebrew-core#437]
brew install source-highlight
configure: error: Could not find a version of the Boost::Regex library!

**Comment by rwhogg** [comment]
Hi @timotheecour : can you please run `brew gist-logs source-highlight` and paste the link here? Thanks!

It builds fine for me (Ubuntu 14.04), although I've seen similar problems with other formulae in the past.

I'm building a bottle for this formula at #438 ; hopefully, that will build correctly and in a few hours you'll be able to install directly from that.

**Comment by timotheecour** [comment]
on ubuntu 16.04.1

https://gist.github.com/anonymous/f14d2c5d09f6f40cd349424497990cc6

**Comment by rwhogg** [comment]
I just attempted to build the bottle again and while it passed on Circle CI, it failed on Travis with the same problem you're seeing.

https://stackoverflow.com/questions/38944868/c-libs-from-ubuntu-16-04-repo-compiler-options provides an interesting point: with C++ projects, it's generally best to use the same compiler, version, and C++ standard for all libraries. This has bitten us a few times to say the least - `libxml++3` has this problem, for example.

I think this is a problem with the GCC 5 Dual ABI. From https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html:
```
If you get linker errors about undefined references to symbols that involve types in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI. 
```

CC @sjackman, I've been thinking that this problem is likely to come up a lot with C++ and we might want to handle it more globally. Lots of ways we could deal with it, from requiring C++ libraries be built from source if you're not using brewed GCC to simply creating a standard C++ caveat of the form "you may want to build this from source".

In the meantime, @timotheecour, you may want to just do a `brew reinstall -s boost` and then attempt this install again. I apologize that this is such a complicated issue.

**Comment by sjackman** [comment]
I need to better understand which versions of GCC with which `-std` options conform to which ABI. It may be the case that C++ programs must be compiled using the brewed GCC, and I'd be okay with that. We need to know which formula depend on C++, and that'd be pretty easy to determine with `brew test-bot` now that we have `brew linkage` working.
