### ISSUE TITLE
Can't install glibc (but have gcc 6.1 installed) (RHEL)

### ISSUE THREAD

**Issue by ElliotWay** [Linuxbrew/homebrew-core#4803]
- [x] Confirmed this is a problem with one, specific formula (The problem's with glibc, though obviously in practice this breaks everything else.)
- [x] If you have a macOS system...
- [x] Ran `brew update` and retried your prior step? (This gives an error message from git, because I can't brew install a newer version.)
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? (As best I can. Maybe some of this is the problem?)
- [x] Ran `brew gist-logs glibc` 
https://gist.github.com/651b594c33bd0a290fca1f88ac1713c0

I'm trying to install the dependencies I need for something else, but they all seem to require glibc, which fails with this error. The error is apparently actually a warning, and I can't see what the warning is.

I'm on a RHEL system that I don't have sudo access to (actually, I have partial sudo permissions so sudo -v succeeds, but I mostly can't use it).
It's part of a Slurm system, where this is all going on on the head node - I don't think this would cause problems on its own, but what do I know.
A quirk of this system is that my home directory is in /data/home, not /home.

gcc 6.1 is installed as Slurm module in this system, but apparently this didn't include a more recent version of glibc than was originally installed (2.12). The original version of gcc is also still there (4.4.7).
I've linked that original version to ~/.linuxbrew/bin/gcc-4.4 and the 6.1 version to ~/.linuxbrew/bin/gcc-6. Trying to install glibc without the gcc-6 link gives "cannot be built with available compilers."

I'm in contact with my sysadmin, but I thought you might have a guess as to what's causing the problem?

**Comment by ndevenish** [comment]
I've just had exactly the same problem -
 https://gist.github.com/anonymous/9f09c49d4538c0397d76d2f8c4d53d27.

After following the Centos6 [instructions](https://github.com/Linuxbrew/brew/wiki/CentOS6), I found that almost everything was being built from source rather than bottles, so I tried gcc-7, which was available in an importable [module](http://modules.sourceforge.net/), hoping that I could get the initial glibc without jumping through the documented loops.

This caused this error. Luckily, there was also a gcc 4.9 available, and that worked - so it looks like it's a matter of newer compilers adding more warnings (and `glibc` is treating warnings as errors).

So try and see if there's an older GCC available, even if just for the first stages?

**Comment by ElliotWay** [comment]
Thanks for the tip - at least now I know why the newer compiler isn't working.

6.1 seems to be the only gcc I have access to; maybe I can find another workaround.

I tried installing gcc@4.9 as a bottle with --ignore-dependencies, but this unsurprisingly didn't work.

**Comment by ElliotWay** [comment]
I got this working by ignoring my installation of 6.1 entirely and using the fix @tueda figured out in #4077.
