### ISSUE TITLE
Older or fixed version of cmake is required.

### ISSUE THREAD

**Issue by zijuexiansheng** [Linuxbrew/homebrew-core#5294]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Linuxbrew please file a [Pull Request](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md).
To get formulae added or changed that is a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-core/compare
To get formulae added or changed that is not a dependency of a formula in Linuxbrew/homebrew-core submit a Pull Request to https://github.com/Linuxbrew/homebrew-extra/compare
We will close issues requesting formulae changes.

---

Can anyone provide an older version or fixed version of CMake? Sometimes I need to upgrade some formula that depends on CMake to build it. If I have to compile from the source, then I'll also have to upgrade CMake, leading to a chain of upgrading, which leads to a very long compiling time. This is annoying because the program that is going to be compiled is usually small!!! So it would be better to provide an older version of CMake and then the programs/formulas depend on that specific CMake.

In fact, I'd prefer the `brew pin` can really pin the formula, but I read it somewhere that the contributors finally made a decision to make it like this :(

**Comment by iMichka** [comment]
Hi. Linuxbrew just follows the concepts from Homebrew. So these decisions were taken upstream, and we try to follow them as much as possible, to keep the same behaviour under Linux.

We prefer you to use `brew update && brew upgrade`, to keep everything up to date, instead of upgrading just a single package.

If you installed brew under /home/linuxbrew/, brew will download precompiled binaries, so you will not need to wait for stuff to be recompiled. If this is not possible, you need to wait for the compilation to be done. There is nothing we can do about that.

`brew pin` can work, but may also lead to some package breakages in some cases.

I'll close this issue as we can't do anything here. Changes are welcome, but need to be implemented in the mac version first (Homebrew).

What you are trying to do is more something for a package manager like nix (https://nixos.org/nix/). I never tried it out, but it handles way better multiple versions of packages than we do.

**Comment by zijuexiansheng** [comment]
Actually

**Comment by iMichka** [comment]
Actually, that would be implementing a `cmake@3.9` formula. We have that for some formulae, but this is often up to Homebrew to decide what kind of formula they want to have and to keep around. We personally do not like versioned formulae very much.

In your case the best thing to do would be to host this formula on your own tap and to maintain it yourself. This should not be too difficult.
