### ISSUE TITLE
mkvtoolnix doesn't compile

### ISSUE THREAD

**Issue by retokromer** [Linuxbrew/homebrew-core#5545]
FYI: The issue https://github.com/Linuxbrew/homebrew-core/issues/4959 is still of actuality, but it has been closed by the stale bot. See https://github.com/Linuxbrew/homebrew-core/pull/4963 as well.

**Comment by iMichka** [comment]
Just to be clear: I have no clue how to fix this. Somebody needs to contact upstream, provide them a log file and debug this with them. Or somebody needs to find out what is broken.

**Comment by retokromer** [comment]
Thank you for clarifying. Then I’ll give a try.

**Comment by iMichka** [comment]
Mmh wait looking at the log I made some progress, let my try something else before contacting upstream.

**Comment by retokromer** [comment]
Hmm… I see that it claims `xsltproc` is missing, but this is part of `libxml2`.

**Comment by mbunkus** [comment]
The problem with `pugixml` seems to be a bug in `configure`:

`configure` queries `pkg-config` for the existence of the `pugixml` library. In this particular case, `pkg-config` confirms that it knows that module. `configure` assumes that all is well and doesn't check whether or not a test program can be compiled.

However, `configure` does not query `pkg-config` for the `--cflags` and `--libs` for that module. As Homebrew seems to install each and every library in their own subdirectory, the linker won't find the library as that subdirectory is not added to the linker flags.

That this works for distributions where `pugixml` is indeed found by `pkg-config` is simply due to them shipping the library in standard locations such as `/usr/lib` which are searched by the linker anyway.

A workaround is to add `pugixml`'s subdirectory to `--with-extra-libs`.

I'll see to fixing `configure`.

**Comment by mbunkus** [comment]
Huh… I'm wrong.

The `PKG_CHECK_MODULES` macro does set the corresponding variables in `build-config` as I've just verified. This looks more like the output of `pkg-config --libs pugixml` missing the linker flag for the directory where the library is located in.

Can you please post the output of `pkg-config --libs pugixml` and `find /path/to/my/Homebrew -name 'libpugixml*'`?

**Comment by mbunkus** [comment]
…and the content of `build-config`, too, please. Thanks.

**Comment by mbunkus** [comment]
Alright, here's the deal: the `pkg-config` file generated by `pugixml` itself is buggy. On my Arch Linux I configure `pugixml` to install to `~/opt/pugixml`:

```shell
[0 mosu@sweet-chili (master) ~/prog/c/pugixml/build] cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/opt/pugixml -DBUILD_PKGCONFIG=ON
…
[0 mosu@sweet-chili (master) ~/prog/c/pugixml/build] make
…
[0 mosu@sweet-chili (master) ~/prog/c/pugixml/build] make install
…
-- Installing: /home/mosu/opt/pugixml/lib64/pugixml-1.8/libpugixml.a
…
```

Note the path to the library. Now observe the following:

``` shell
[1 mosu@sweet-chili (master) ~/prog/c/pugixml/build] PKG_CONFIG_PATH=$HOME/opt/pugixml/lib/pkgconfig pkg-config --libs pugixml
-L/home/mosu/opt/pugixml/lib/pugixml-1.8 -lpugixml
```

That path, `/home/mosu/opt/pugixml/lib/pugixml-1.8`, does not exist (`lib64` vs `lib`).

Bug in `pugixml`, not in MKVToolNix.

The workaround I've mentioned above should work. What should also work is not having `pugixml` installed at all as MKVToolNix will then use its included copy.
