### ISSUE TITLE
atom

### ISSUE THREAD

**Issue by jney** [Linuxbrew/homebrew-core#6083]
[atom](https://atom.io/) formula is not present (yet) in this repo.
the atom team provides [releases](https://github.com/atom/atom/releases) with deb or rpm format.
i don't see formulas using deb or rpm is there a prefered way to install with such format?

**Comment by iMichka** [comment]
Hi. In fact we try to only package things that are packaged by upstream (homebrew on mac). So the package needs to build from source, amongst other things. Even if that is the case, things like text editors are not shipped by us.

On mac you can probably install it with `brew cask`. Building an equivalent system for Linuxbrew would be great. There were already multiple discussions about this.

But I am not willing to go down that road until somebody wants to work on this (and this somebody/team needs to have a strong commit history here so that I can trust him to continue to work on this in the future). We are in dire need for maintainers and help :)

Closing here because this is not something we do not plan to work on currently. Thanks for the interest though.

**Comment by maxim-belkin** [comment]
Just adding to what @iMichka said: the formulae in thie repo are the ones that macOS users find in `Homebrew/homebrew-core`: we don't add Linux-only formulas here unless they are direct mandatory dependencies. So, if you'd like to see a formula here, submit it upstream to Homebrew/homebrew-core
