### ISSUE TITLE
ghc: building fails on CentOS7

### ISSUE THREAD

**Issue by jpauwels** [Linuxbrew/homebrew-core#6120]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Logs: https://gist.github.com/5232181ba15676d3e30bfc9ac4e7cdf7
`brew install ghc` fails on CentOS7, not reproducible on macOS High Sierra

```
# The .dll case calls STRIP_CMD explicitly, instead of `install -s`, because
# on Win64, "install -s" calls a strip that doesn't understand 64bit binaries.
# For some reason, this means the DLLs end up non-executable, which means
# executables that use them just segfault.
/usr/bin/install -c -m 755 -d  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts"
for i in  rts/dist/build/libHSrts.a rts/dist/build/libHSrts_p.a rts/dist/build/libHSrts-ghc8.2.2.so rts/dist/build/libHSrts_l.a rts/dist/build/libHSrts_debug.a rts/dist/build/libHSrts_thr.a rts/dist/build/libHSrts_thr_debug.a rts/dist/build/libHSrts_thr_l.a rts/dist/build/libHSrts_thr_p.a rts/dist/build/libHSrts_debug-ghc8.2.2.so rts/dist/build/libHSrts_thr-ghc8.2.2.so rts/dist/build/libHSrts_thr_debug-ghc8.2.2.so rts/dist/build/libHSrts_l-ghc8.2.2.so rts/dist/build/libHSrts_thr_l-ghc8.2.2.so rts/dist/build/libffi.so.6.0.4 rts/dist/build/libffi.so.6 rts/dist/build/libffi.so rts/dist/build/libCffi.a rts/dist/build/libCffi_p.a rts/dist/build/libCffi_l.a rts/dist/build/libCffi_debug.a rts/dist/build/libCffi_thr.a rts/dist/build/libCffi_thr_debug.a rts/dist/build/libCffi_thr_l.a rts/dist/build/libCffi_thr_p.a; do case $i in *.a) /usr/bin/install -c -m 644  $i  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts"; true  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts"/`basename $i` ;; *.dll) /usr/bin/install -c -m 755  $i  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts" ; strip  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts"/`basename $i` ;; *.so) /usr/bin/install -c -m 755  $i  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts" ;; *.dylib) /usr/bin/install -c -m 755  $i  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts";; *) /usr/bin/install -c -m 644  $i  "/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/rts"; esac; done
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install "strip" '' '/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary' '/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2' '/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/share/doc/ghc-8.2.2/html/libraries' 'v p dyn'
Installing library in /tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/ghc-prim-0.5.1.1
strip: /tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/ghc-prim-0.5.1.1/stFXf4g9: Not enough room for program headers, try linking with -N
strip:/tmp/ghc-20180216-48235-1ymwlkk/ghc-8.2.2/binary/lib/ghc-8.2.2/ghc-prim-0.5.1.1/stFXf4g9[.note.gnu.build-id]: Bad value
make[1]: *** [install_packages] Error 1
make: *** [install] Error 2
```

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. This is a duplicate of #4413.

The actual error is: `strip: Not enough room for program headers, try linking with -N`

I am currently not working on this. There may be other people interested on fixing this though.

**Comment by iMichka** [comment]
@ebzheng @dchiu911 The discussion can be continued here.

As we seem to be stuck here, I would recommend to try to contact the ghc developers to get some help. I am running out of ideas.

**Comment by ebzheng** [comment]
Thanks for pinging me!

@jpauwels - What sort of environment are you running in? Since you're using linuxbrew, I suspect you're probably in a shared cluster environment. Is there any chance that you're running into a inode or file usage limit?

**Comment by iMichka** [comment]
Actually our build bot is fine: we run on circle.ci with a ubuntu 16.04 docker image. We could build bottles there, and I can also build `ghc` locally.

The reports of this bug come from people running centos 7 (and 6?). Not sure on what hardware.

**Comment by ebzheng** [comment]
Does the Travis CI also use Ubuntu 16.04? When I submitted my PR last month, Travis threw the same error too. I was also able to get a similar error ("No space left on device") on an Ubuntu 16.04 AWS instance, so I suspect CentOS might be a red herring.

My suspicion is that there may be a file system issue - our cluster has a fairly aggressive disk and inode quota; CentOS users may well be working on shared systems with similar limits. Finally, I didn't allocate my test AWS instance with a lot of storage.

I suppose I could try again on AWS with much more storage and see what happens (and/or log disk usage during a build). How much storage does the circle.ci build bot have available?

**Comment by iMichka** [comment]
Yeah; building `ghc` is quite disk and memory expensive.

For the disk size:
https://discuss.circleci.com/t/workaround-for-running-out-of-disk-space/3648

```
Sometimes your builds fail because you are running out of disk space. This is a tricky problem because we do not necessary limit the amount of disk that you are able to use. In addition, the total amount of disk space that is available during a build depends on the underlying VM. Since this is a variable number there can be significant differences in total available disk space across builds.
```

Looking at the figures in the discussion, we have multiple gigabytes available.

Checking disk usage during the build would be great, to see how much is being used. Also, if the RAM runs full, the build probably starts swapping ... which may fill the disk faster.

On circle, we build with `ENV["MAKEFLAGS"] = "-j6" if ENV["CIRCLECI"]`, to reduce the memory usage (because we have only 4Gb and no swap). Maybe this would actually help too on systems with limited RAM and disk space?

**Comment by ebzheng** [comment]
Hmm... RAM probably isn't an issue on our cluster here (if it is, I'm not sure how anyone is building it successfully!)

I have a new system that needs burning in, so I'll give a ghc build a shot and see how that goes.

**Comment by ebzheng** [comment]
So in forcing a ghc build (vs using the bottle) on a new 16.04 Ubuntu install on a workstation, I have the following anecdata, summarized by eyeball:

- Memory usage appears trivial and doesn't seem to appreciably increase over the course of the build, so swapping is unlikely.
 - Global disk usage, taken approximately every 1-3 seconds during the build, increases on the order of 3-4 GB, which while large, isn't sufficiently so to raise issues.
 - Global inode usage, taken similarly, increases on the order of 30K items, which depending on the location of the temporary files, could actually be causing problems (our HPC has a home folder inode limit of only 100K, which I've run into before).

**Comment by iMichka** [comment]
Inodes may definitely be a problem. This has bitten me in other occasions. If you have a lot of small files, and depending on the number of inodes / block size on the disk, you can hit the inode limit before the disk being "full". 30K is already a lot. Depending on the disk usage for other things, the limit can be hit quite fast.

It would be good to know how many inodes are free on @jpauwels system?

**Comment by iMichka** [comment]
There is also an older discussion there: https://github.com/NixOS/patchelf/issues/10
Probably worth reading too

**Comment by jpauwels** [comment]
I'm indeeed compiling on a shared computing server in a university setting. RAM shouldn't be a problem, the server has 64GB and I tried again when I was the only user. Our home directories are "floating" on shared storage. An increase in a couple of GB storage shouldn't risk running into any quotas. Plenty of inodes free as well, it seems:
```
Filesystem              Inodes    IUsed     IFree IUse% Mounted on
brie:/v8/users/johan 134217728 18479225 115738503   14% /homes/johan
```
Having a bottle would help me out for now.

**Comment by iMichka** [comment]
@sjackman we still do run `patchelf` on everything?
I do believe the bug is this one https://github.com/NixOS/patchelf/issues/10

Fixes have been pushed; but there was no new `patchelf` release since:
https://github.com/NixOS/patchelf/pull/117
https://github.com/NixOS/patchelf/pull/127

I see also some reports on these pull requests that it is not completely fixed.

@sjackman could we make a test run of a build without patchelf locally, so that somebody can test if this is related to patchelf.

**Comment by iMichka** [comment]
Another solution would be to look at the source code of `ghc` and remove the `strip` call.

**Comment by sjackman** [comment]
> The actual error is: `strip: Not enough room for program headers, try linking with -N`

`patchelf` and `strip` may not play nicely together. For troubleshooting, is it possible to disable stripping when configuring `ghc`?

**Comment by winni2k** [comment]
I'm running into this error as well on CentOS Linux release 7.4.1708 (Core).

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle ghc`, but no promises.

If it's an option for you, you could open a ticket with your systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew` for the purpose of sharing software that is used by your group.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by iMichka** [comment]
And I would be willing to review a patch which removes the strip call from ghc. I do not have time to work on this myself though.

**Comment by sjackman** [comment]
Here's the Patchelf bug report https://github.com/NixOS/patchelf/issues/10: Section re-ordering confuses `strip`

**Comment by shivakumargn** [comment]
I tried brew on CentOS-7 and hit this very issue. Should I open a new issue?

**Comment by iMichka** [comment]
No need to open a new issue. This one has just been closed as stale because nobody is working on this. Somebody needs to fix it

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `ghc`.
Another possible workaround for you is `brew install --force-bottle ghc`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
