### ISSUE TITLE
Issue with `watchman` bottle.

### ISSUE THREAD

**Issue by deanmarano** [Linuxbrew/homebrew-core#956]
When using the bottle for watchman, it seems that it tries to create a folder based on the username. The username seems to be cached somewhere into the bottle, so it tries to write a file to /home/linuxbrew/... and fails.

```bash
$ echo $USER
dean
$ watchman
2016-09-29T00:10:04,137: [326653760] while computing sockname: failed to create /home/linuxbrew/.linuxbrew/var/run/watchman/dean-state: No such file or directory
```

Building from source solved the problem.

`brew gist-logs <formula>` - https://gist.github.com/73da04960176a0fc29564f7f0c60dd59

**Comment by rwhogg** [comment]
Wow, thanks for catching!

The path you mentioned comes from this line:

```ruby
"--enable-statedir=#{var}/run/watchman"
```
Which appears to get hardcoded into the bottle.

We've had problems like this before and they were fixed just by making the bottle not be `cellar :any` on Linux. As a quick fix, I can do that.

**Comment by deanmarano** [comment]
Awesome! Thanks for the quick fix.

**Comment by sjackman** [comment]
Any idea why this issue doesn't affect Mac OS? Not a high priority, just curious.

**Comment by rwhogg** [comment]
I'd be shocked if it *doesn't* affect Mac OS. It's just far less likely to be a problem there since the installer defaults to the same place the bottle is built for, unlike with Linux.

We should probably report this upstream if they don't already know about it, but I didn't want to change the behaviour of the Mac bottles just for Linuxbrew.

**Comment by sjackman** [comment]
Right of course. Makes sense.
